READ MACRO         
MOV AH,08H           
INT 21H             
ENDM

PRINT MACRO CHAR    
MOV DL,CHAR         
MOV AH,02H          
INT 21H
ENDM 

PRINT_STR MACRO STRING   
MOV DL,OFFSET STRING     
MOV AH,09H
INT 21H
ENDM 

EXIT MACRO               
MOV AX,4C00H             
INT 21H                                         
ENDM     

DATA SEGMENT
   NEW_LINE DB 0AH,0DH,'$'
  
DATA ENDS

NUMBERS   DB  14  DUP(?)   
UPPERCASES  DB  14  DUP(?)
LOWERCASES      DB  14  DUP(?)

   A DW 1       ;ARXIKOPOIHSH TOU METRHTH TWN ARI8MWN
   K DW 1       ;TWN KEFALAIWN
   P DW 1       ;TWN PEZWN
   E DW 0       ;TWN EGKURWN STOIXEIWN 
   MAX1 DB 0     ;TOU MEGISTOU ARI8MOU1
   MAX2 DB 0     ;TOU MEGISTOU ARI8MOU2  
    POS1 DB 0   ;THS  POSS TOU MAX1
    POS2 DB 0   ;THS  POSS TOU MAX2
   TEMP DW 0
   

CODE SEGMENT
ASSUME CS:CODE,DS:DATA,SS:STACK  

PUSH AX

START: 
    CMP E,0EH 
    JE GROUP1    
    READ     
    CMP AL,'='
    JE  EXIT
    CMP AL,0DH        ;SUGKRINW ME ENTER
    JE GROUP2
    CMP AL,20H        ;SUGKRINW ME SPACE
    JE SPACE
    CMP AL,30H        ;SUGKRINW ME TO MHDEN
    JL START
    CMP AL,39H        ;SUGKRINW AN EINAI MIKROTERO H ISO TOU 9
    JLE  NUMBER
    CMP AL,'A'        ;SUGKRINW AN EINAI MIKROTERO TOU A
    JL START
    CMP AL,'Z'        ;SUGKRINW AN EINAI TOU MIKROTERO H ISO TOU Z
    JLE UPPERCASE
    CMP AL,'a'        ;SUGKRINW AN EINAI MIKROTERO TOU a
    JL START
    CMP AL,'z'
    JLE LOWERCASE          ;SUGKRINW AN EINAI MIKROTERO H ISO TOU z
    JMP START

GROUP1:
    READ
    CMP AL,0DH        ;PATAW ENTER
    JNE GROUP1    
GROUP2:
    PRINT_STR NEW_LINE  ;ALLAGH GRAMMHS
    MOV CX,01H          ;XEKINAW APO TH 8ESH ENA TWN PINAKWN
COMPARE1:
    CMP CX,A
    JL DISPLAY1
    PRINT ' '
    MOV CX,01H
   JMP COMPARE2
COMPARE2:
    CMP CX,K
    JL DISPLAY2
    PRINT ' '
    MOV CX,01H
    JMP COMPARE3
COMPARE3:
    CMP CX,P
    JL DISPLAY3 
    JMP MAX_NUMBER1      
    
DISPLAY1:
    MOV DI,CX
    PRINT NUMBERS[DI]
    INC CX
    JMP COMPARE1

DISPLAY2:
    MOV DI,CX
    PRINT UPPERCASES[DI]
    INC CX
    JMP COMPARE2
    
DISPLAY3:
    MOV DI,CX
    PRINT LOWERCASES[DI]
    INC CX
    JMP COMPARE3    


SPACE:
    PRINT AL
    INC E
    JMP START    
    
NUMBER:                ;DISPLAY KAI APO8HKEUSH TOU ARI8MOU
    PRINT AL
    INC E   
    MOV DI,A
    MOV NUMBERS[DI],AL
    INC A
    JMP START 
    
UPPERCASE:               ;DISPLAY KAI APO8HKEUSH TOU UPPERCASEU
    PRINT AL 
    INC E 
    MOV DI,K
    MOV UPPERCASES[DI],AL
    INC K
    JMP START
    
LOWERCASE:                   ;DISPLAY KAI APO8HKEUSH TOU LOWERCASEU
    PRINT AL 
    INC E   
    MOV DI,P
    MOV LOWERCASES[DI],AL
    INC P
    JMP START    
    
MAX_NUMBER1:
    MOV CX,01H
    MOV DI,CX           ;3EKINW APO THN ARXH TOU PINAKA NUMBERS 
    MOV BL,MAX1
    MOV BL,NUMBERS[DI]  ;FIND_MAX TO PRWTO STOIXEIO TOU PINAKA STON MAX1
    MOV MAX1,BL
    MOV  POS1,01H  
NEXT:
    INC CX
    CMP CX,A             ;AN EXEI FTASEI STO TELOS TOU PINAKA NUMBERS
    JG MAX_NUMBER2       ;AN EXEI FTASEI TOTE PSAXNOYME TON MAX2
    MOV DI,CX            ;AN OXI SUNEXIZOUME KAI KANOUME TH SUGKRISH
    MOV BL,MAX1
    CMP NUMBERS[DI],BL     ;SUGKRINW ME TO EPOMENO STOIXEIO 
    JG FIND_MAX1
    JMP NEXT
   
MAX_NUMBER2:
    MOV CX,01H
    CMP  POS1,01H
    JNE SWAP           ;AN MAX1 DEN EINAI TO PRWTO STOIXEIO TOTE KANOUME ENALLAGH 1ou STOIXEIOU ME MAX1
                         ;KAI TIS 8ESEIS TOUS ANTISTOIXA
NEXT3:                   
    MOV CX,02H           ;ARXIZOUME TH SUGKRISH APO TO 2o STOIXEIO
    MOV  POS2,02H
    MOV DI,CX  
    MOV BL,MAX2
    MOV BL,NUMBERS[DI]
    MOV MAX2,BL 
    
NEXT2:
    INC CX 
    CMP CX,A
    JG DISPLAY4 ;EXW FTASEI STO TELOS TOU PINAKA ARA PAW NA EMFANISW
    MOV DI,CX 
    MOV BL,MAX2
    CMP NUMBERS[DI],BL
    JG FIND_MAX2   
    JMP NEXT2
      
SWAP:                    ;ENALLAGH 1ou STOIXEIOU ME MAX1
    MOV CL, POS1 
    MOV DI,CX
    MOV BL,NUMBERS[01H]
    MOV NUMBERS[DI],BL
    MOV BL,MAX1
    MOV NUMBERS[01H],BL 
    JMP NEXT3
          
DISPLAY4:
    MOV BL, POS1
    MOV CL, POS2
    CMP BL,CL 
    PRINT_STR NEW_LINE
    JGE DISPLAY5           ;SUGKRINEI POIO HR8E PRWTO KAI DEUTERO KAI TA EMFANIZEI
    PRINT MAX1
    PRINT MAX2
    PRINT_STR NEW_LINE
    JMP INIT_ARRAYS
DISPLAY5:
    PRINT MAX2
    PRINT MAX1
    PRINT_STR NEW_LINE 
    
INIT_ARRAYS:      ;MHDENISMOS PINAKWN GIA THN EPOMENH FORA
    MOV TEMP,00H
    MOV CX,TEMP
NUMBERS_ARRAYS: 
    MOV DI,CX
    MOV NUMBERS[DI],00H 
    INC CX
    CMP CX,A
    JLE NUMBERS_ARRAYS
    MOV CX,TEMP
UPPERCASE_ARRAYS:
    MOV DI,CX
    MOV UPPERCASES[DI],00H
    INC CX
    CMP CX,K
    JLE UPPERCASE_ARRAYS
    MOV CX,TEMP
LOWERCASE_ARRAYS:
    MOV DI,CX
    MOV LOWERCASES[DI],00H
    INC CX
    CMP CX,P
    JLE LOWERCASE_ARRAYS 
    MOV A,01H
    MOV K,01H
    MOV P,01H
    MOV MAX1,00H
    MOV MAX2,00H
    MOV  POS1,00H
    MOV  POS2,00H
    MOV E,00H
    JMP START    
 
FIND_MAX1:                ;GIA MAX1
    MOV BL,NUMBERS[DI]
    MOV MAX1,BL
    MOV  POS1,CL
    JMP NEXT 
    
FIND_MAX2:               ;GIA MAX2
    MOV BL,MAX2
    MOV BL,NUMBERS[DI]
    MOV MAX2,BL
    MOV  POS2,CL
    JMP NEXT2 
    

    POP AX
    
EXIT:
    EXIT
            
END
